const express = require('express');
const router = express.Router();

const { followArtist } = require('./functions.js');
const { checkUserLoggedIn } = require('./functions.js');
const { showHomePage } = require('./functions.js');
const { showGalleryPage } = require('./functions.js');
const { showLoginPage } = require('./functions.js');
const { showCreateAccountPage } = require('./functions.js');
const { loginUser } = require('./functions.js');
const { checkUserLoggedOut } = require('./functions.js');
const { createAccount } = require('./functions.js');
const { showGalleryData } = require('./functions.js');
const { postComment } = require('./functions.js');
const { likeArtwork } = require('./functions.js');
const { checkTitleExists } = require('./functions.js');
const { addArtwork } = require('./functions.js');
const { showAddArtPage } = require('./functions.js');
const { showAddWorkshopPage } = require('./functions.js');
const { postWorkshop } = require('./functions.js');
const { checkUserIsArtist } = require('./functions.js');
const { showWorkshopPages } = require('./functions.js');
const { showArtistPageOne } = require('./functions.js');
const { showWorkshopPage } = require('./functions.js');
const { enrollWorkshop } = require('./functions.js');
const { searchArtworks } = require('./functions.js');
const { showSearchPage } = require('./functions.js');
const { deleteLike } = require('./functions.js');
const { deleteComment } = require('./functions.js');
const { showProfile } = require('./functions.js');
const { switchAccountType } = require('./functions.js');
const { unfollowArtist } = require('./functions.js');
const { logoutUser } = require('./functions.js');
const { showArtistPage } = require('./functions.js');

router.get('/', showHomePage);
router.get('/gallery', showGalleryPage);
router.post('/gallery', checkUserLoggedIn, addArtwork);
router.get('/gallery/:id', showGalleryData);
router.get('/login', showLoginPage);
router.put('/login', checkUserLoggedOut, loginUser);
router.post('/login', checkUserLoggedOut, createAccount);
router.get('/newaccount', showCreateAccountPage);
router.post('/switchAccount', switchAccountType);
router.get('/artistPage', showArtistPage);
router.get('/addArt', showAddArtPage);
router.get('/artist/:a', showArtistPageOne);
router.post('/comments', checkUserLoggedIn, postComment);
router.delete('/comments', deleteComment);
router.post('/likes', checkUserLoggedIn, likeArtwork);
router.delete('/likes', deleteLike);
router.get('/addWorkShop', showAddWorkshopPage);
router.post('/workshop', checkUserLoggedIn, checkUserIsArtist, postWorkshop);
router.get('/workshop', showWorkshopPages);
router.get('/workshop/:a', showWorkshopPage);
router.post('/enroll', checkUserLoggedIn, enrollWorkshop);
router.post('/follow', checkUserLoggedIn, followArtist);
router.delete('/follow', unfollowArtist);
router.put('/search', searchArtworks);
router.get('/search', showSearchPage);
router.put('/checkTitle', checkTitleExists);
router.get('/profile', showProfile);
router.post('/logout', logoutUser);

module.exports = router;